version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chat_db
    environment:
      POSTGRES_DB: chat_dev
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_pass
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
