"""added DateTime with timezone on RefreshToken

Revision ID: 3a4f49c57658
Revises: 453928145398
Create Date: 2025-12-09 16:14:48.605409

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a4f49c57658"
down_revision: str | Sequence[str] | None = "453928145398"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE refresh_tokens "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE created_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE refresh_tokens "
        "ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN expires_at IS NULL THEN NULL "
        "ELSE expires_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE refresh_tokens "
        "ALTER COLUMN revoked_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN revoked_at IS NULL THEN NULL "
        "ELSE revoked_at AT TIME ZONE 'UTC' END;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE refresh_tokens "
        "ALTER COLUMN revoked_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN revoked_at IS NULL THEN NULL "
        "ELSE (revoked_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE refresh_tokens "
        "ALTER COLUMN expires_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN expires_at IS NULL THEN NULL "
        "ELSE (expires_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE refresh_tokens "
        "ALTER COLUMN revoked_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN revoked_at IS NULL THEN NULL "
        "ELSE (revoked_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE refresh_tokens "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE (created_at AT TIME ZONE 'UTC') END;"
    )
    # ### end Alembic commands ###
