"""timezone aware

Revision ID: 453928145398
Revises: 1e235870d479
Create Date: 2025-12-09 09:00:33.047189

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "453928145398"
down_revision: str | Sequence[str] | None = "1e235870d479"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE conversation_participants "
        "ALTER COLUMN joined_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN joined_at IS NULL THEN NULL "
        "ELSE joined_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE conversation_participants "
        "ALTER COLUMN last_read_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN last_read_at IS NULL THEN NULL "
        "ELSE last_read_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE conversations "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE created_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE friendships "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE created_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE friendships "
        "ALTER COLUMN accepted_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN accepted_at IS NULL THEN NULL "
        "ELSE accepted_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE message_receipts "
        "ALTER COLUMN delivered_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN delivered_at IS NULL THEN NULL "
        "ELSE delivered_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE message_receipts "
        "ALTER COLUMN seen_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN seen_at IS NULL THEN NULL "
        "ELSE seen_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE messages "
        "ALTER COLUMN sent_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN sent_at IS NULL THEN NULL "
        "ELSE sent_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE messages "
        "ALTER COLUMN read_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN read_at IS NULL THEN NULL "
        "ELSE read_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE users "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE created_at AT TIME ZONE 'UTC' END;"
    )
    op.execute(
        "ALTER TABLE users "
        "ALTER COLUMN last_login TYPE TIMESTAMP WITH TIME ZONE "
        "USING CASE WHEN last_login IS NULL THEN NULL "
        "ELSE last_login AT TIME ZONE 'UTC' END;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE users "
        "ALTER COLUMN last_login TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN last_login IS NULL THEN NULL "
        "ELSE (last_login AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE users "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE (created_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE messages "
        "ALTER COLUMN read_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN read_at IS NULL THEN NULL "
        "ELSE (read_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE messages "
        "ALTER COLUMN sent_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN sent_at IS NULL THEN NULL "
        "ELSE (sent_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE message_receipts "
        "ALTER COLUMN seen_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN seen_at IS NULL THEN NULL "
        "ELSE (seen_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE message_receipts "
        "ALTER COLUMN delivered_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN delivered_at IS NULL THEN NULL "
        "ELSE (delivered_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE friendships "
        "ALTER COLUMN accepted_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN accepted_at IS NULL THEN NULL "
        "ELSE (accepted_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE friendships "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE (created_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE conversations "
        "ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN created_at IS NULL THEN NULL "
        "ELSE (created_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE conversation_participants "
        "ALTER COLUMN last_read_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN last_read_at IS NULL THEN NULL "
        "ELSE (last_read_at AT TIME ZONE 'UTC') END;"
    )
    op.execute(
        "ALTER TABLE conversation_participants "
        "ALTER COLUMN joined_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING CASE WHEN joined_at IS NULL THEN NULL "
        "ELSE (joined_at AT TIME ZONE 'UTC') END;"
    )
    # ### end Alembic commands ###
